#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTART APP SERVICES
#=================================================
ynh_script_progression "Applying configuration..."

ynh_config_add --template="env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

ynh_systemctl --service="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Configuration of $app completed"
