#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICES
#=================================================
ynh_script_progression "Removing services..."

ynh_systemd_action --service_name="$app" --action="stop"
ynh_remove_systemd_config --service="$app"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_remove_nginx_config

#=================================================
# REMOVE REDIS DB
#=================================================
ynh_script_progression "Removing Redis database..."

redis_db=$(ynh_app_setting_get --key=redis_db)
redis-cli -n "$redis_db" FLUSHDB 2>/dev/null || true

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
