#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SETUP S3
#=================================================
ynh_script_progression "Setting up S3..."
setup_s3

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

ynh_exec_as_app mkdir -p "$install_dir/_build/venv"
ynh_exec_as_app mkdir -p "$install_dir/_build/frontend"
ynh_exec_as_app mkdir -p "$install_dir/_build/data/static"

NVM_DIR=$(ynh_exec_as_app bash -c 'echo "$HOME/.nvm"')
NODE_VERSION=22

pushd "$install_dir/src/backend"
    ynh_exec_as_app python3 -m venv "$install_dir/_build/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/_build/venv/bin/pip3" install --upgrade pip setuptools wheel uv
    ynh_hide_warnings ynh_exec_as_app "$install_dir/_build/venv/bin/uv" sync --locked --no-dev
popd

# Mail builder
pushd "$install_dir/src/mail"
    ynh_hide_warnings ynh_exec_as_app bash -c "source $NVM_DIR/nvm.sh && NODE_VERSION=$NODE_VERSION nvm exec yarn install"
    ynh_hide_warnings ynh_exec_as_app bash -c "source $NVM_DIR/nvm.sh && NODE_VERSION=$NODE_VERSION NODE_ENV=production nvm exec yarn build"
popd

pushd "$install_dir/src/backend"
    # Collect the static resources
    ynh_exec_as_app DATA_DIR="$install_dir/_build/data" DJANGO_CONFIGURATION=Build DJANGO_SECRET_KEY=Dummy \
        STATIC_ROOT="$install_dir/src/backend" \
        "$install_dir/_build/venv/bin/uv" run manage.py collectstatic --noinput

    # Generate compiled translation messages
    ynh_exec_as_app DJANGO_CONFIGURATION=Build \
        "$install_dir/_build/venv/bin/uv" run manage.py compilemessages

    rdfind -makesymlinks true -followsymlinks true -makeresultsfile false "$install_dir/_build/data/static"
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH SUPERUSER;"
    # Setup the database
    ynh_hide_warnings ynh_exec_as_app \
        DJANGO_CONFIGURATION=Production \
        DB_NAME=$db_name DB_USER=$db_name DB_PASSWORD=$db_pwd \
        "$install_dir/_build/venv/bin/uv" run manage.py migrate
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH NOSUPERUSER;"
popd

ynh_script_progression "Setting up frontend source files..."

pushd "$install_dir/src/frontend"
    ynh_hide_warnings ynh_exec_as_app bash -c "source $NVM_DIR/nvm.sh && NODE_VERSION=$NODE_VERSION nvm exec yarn install"
    pushd "./apps/drive"
        ynh_hide_warnings ynh_exec_as_app bash -c "source $NVM_DIR/nvm.sh && NODE_VERSION=$NODE_VERSION NODE_ENV=production nvm exec yarn build"
    popd
    mv ./apps/drive/out "$install_dir/_build/frontend" 2>/dev/null
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE APP CONFIG
#=================================================
ynh_script_progression "Updating application configuration..."

ynh_config_add --template="env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

ynh_config_add --template="gunicorn_drive.py" --destination="$install_dir/gunicorn_drive.py"

#=================================================
# UPDATE SYSTEMD
#=================================================
ynh_script_progression "Updating systemd service..."

ynh_config_add --template="systemd.service" --destination="/etc/systemd/system/$app.service"
systemctl daemon-reload
ynh_systemctl --service="$app" --action="enable"

#=================================================
# UPDATE NGINX
#=================================================
ynh_script_progression "Updating nginx configuration..."

ynh_config_add --template="nginx.conf" --destination="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTART SERVICES
#=================================================
ynh_script_progression "Restarting services..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
